CREATE TABLE tickets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(30) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    category ENUM('BUG','ENHANCEMENT','FEATURE_REQUEST') NOT NULL,
    priority ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
    severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'MEDIUM',
    status ENUM('NEW','UNDER_REVIEW','ASSIGNED','IN_PROGRESS','WAITING_FOR_CLIENT',
                'RESOLVED','UNDER_QA','VERIFIED','CLOSED','REOPENED') DEFAULT 'NEW',
    application_module VARCHAR(100),
    environment ENUM('PRODUCTION','UAT','TEST') NOT NULL,
    version VARCHAR(50),
    browser VARCHAR(100),
    steps_to_reproduce TEXT,
    expected_result TEXT,
    actual_result TEXT,
    raised_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT,
    sla_deadline TIMESTAMP,
    sla_breached BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (raised_by_id) REFERENCES users(id),
    FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);